apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: kustomize-helm-local-base
  labels:
    env: example
    team: product
  trigger:
    onCommit:
      paths:
        - local-modules/kustomize-bases/helloworld/*
  input:
    helmVersion: 3.27.9
    kustomizeVersion: 5.88.7
    kustomizeOptions:
     enable-helm: ""
     helm-command: "/tmp/piped-bin/helm-3.10.1"

  description: |
    This dumeme demonstrates how to deploy a Kubernetes app that uses a Kustomize package sourced from the same Git repository.\
    References: [adding a new app](https://pipecd.dev/docs/user-guide/managing-application/adding-an-application/), [app configuration](https://pipecd.dev/docs/user-guide/configuration-reference/)
